export const COMPILATION_GET_LIST_START = 'compilation/getListStart'
export const COMPILATION_GET_LIST_SUCCESS = 'compilation/getListSuccess'
export const COMPILATION_GET_LIST_FAIL = 'compilation/getListFail'
export const COMPILATION_GET_ITEM_START = 'compilation/getItemStart'
export const COMPILATION_GET_ITEM_SUCCESS = 'compilation/getItemSuccess'
export const COMPILATION_GET_ITEM_FAIL = 'compilation/getItemFail'
export const COMPILATION_ADD_ITEMS_TO_LIST_START = 'compilation/addItemsToListStart'
export const COMPILATION_ADD_ITEMS_TO_LIST_SUCCESS = 'compilation/addItemsToListSuccess'
export const COMPILATION_ADD_ITEMS_TO_LIST_FAIL = 'compilation/addItemsToListFail'
export const COMPILATION_REMOVE_ITEMS_FROM_LIST_START = 'compilation/removeItemsFromListStart'
export const COMPILATION_REMOVE_ITEMS_FROM_LIST_SUCCESS = 'compilation/removeItemsFromListSuccess'
export const COMPILATION_REMOVE_ITEMS_FROM_LIST_FAIL = 'compilation/removeItemsFromListFail'

export const COMPILATION_SET_LIST = 'compilation/setList'
export const COMPILATION_SET_STRUCTURAL_CONDITION = 'compilation/setStructuralCondition'
